# Generated by Django 5.1.2 on 2024-10-20 04:44

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_person_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='dtend',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='schedule',
            name='dtstart',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='friend_name',
            field=models.CharField(default=datetime.datetime(2024, 10, 20, 4, 43, 8, 614367, tzinfo=datetime.timezone.utc), max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='ical',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='schedule',
            name='location',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='summary',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
